### ISSUE TITLE
allow wildcard in some commands

### ISSUE THREAD

**Issue by isaiasanchez** [uptimejp/postgres-toolkit#3]
It's a very nice tool but i would like to be able to use wildcards in some commands like pg_dump use to dump a set of tables using a prefix for example.

pt-table-usage -d sample -n public -t tbl_*

**Comment by snaga** [comment]
Actually, it is the one of the features I dropped just before the first release.
I tried to implement the regular expression to specify object names.
And I will try it again in the next version.
Which do you prefer to have: wildcard or regexp?

**Comment by isaiasanchez** [comment]
wildcard id good, but regexp will be great!

**Comment by snaga** [comment]
I think regexp would be easier because it can be implemented with just passing a regexp pattern via command-line argument.

**Comment by snaga** [comment]
I think regexp would be easier because it can be implemented with just passing a regexp pattern via command-line argument to the regexp module of python.

**Comment by isaiasanchez** [comment]
I'm agree.

**Comment by snaga** [comment]
Added regexp support in pt-table-usage, pt-index-usage and pt-set-tablespace on the develop branch. f8b5ccfb820cc039ad3b51cfb942ad698aa87e7e
So, they will be coming in the next release.
