### ISSUE TITLE
verifychecksum: In case of checksum mismatch, expected and actual are reversed in error message

### ISSUE THREAD

**Issue by mbanck** [uptimejp/postgres-toolkit#48]

**Comment by mbanck** [comment]
patch for this:

```
--- verifychecksum.c.orig       2018-01-23 14:12:23.000000000 +0100
+++ verifychecksum.c.new        2018-01-23 14:35:30.000000000 +0100
@@ -23,7 +23,7 @@
   if (phdr->pd_checksum != checksum)
     {
       printf("%s: blkno %d, expected %x, found %x\n",
-            filepath, blkno, checksum, phdr->pd_checksum);
+            filepath, blkno, phdr->pd_checksum, checksum);
       return FALSE;
     }
 ```

**Comment by snaga** [comment]
In this case, `phdr->pd_checksum` is a stored value in the page header and `checksum` is a calculated (on-the-fly) value from the page content. Here, the latter one should be treated as the correct checksum.

So, I handle `phdr->pd_checksum` as `found`, and `checksum` as `expected`.

Doesn't it make sense?

**Comment by mbanck** [comment]
I was looking at it from Postgres' perspective: it has stored `phdr->pd_checksum` in the page header, so it expects this checksum to be there. But actually, we found `checksum`.

**Comment by snaga** [comment]
I see.
Need more time to look for more appropriate words.

**Comment by snaga** [comment]
How about "page header" for `phdr->pd_checksum` and "calculated" as `checksum`?
Does it make sense?

**Comment by mbanck** [comment]
Sounds good to me, yeah.

**Comment by snaga** [comment]
Committed. 9ef3e488e6da1f8e159268b8f929c80f5d85e3d4

**Comment by snaga** [comment]
Merged. #60
